### ISSUE TITLE
hubot wiki being deprecated, make sure README.md reflects everything from there

### ISSUE THREAD

**Issue by technicalpickles** [lazerwalker/hubot-imessage#1]
Hi there!

We've been working to deprecate the hubot wiki because it gets out of date real quick. See github/hubot#429 for the background, and https://github.com/github/hubot/issues/531 for tracking the wiki update/removing

It looks like this repo has a pretty thorough README, but I wanted to check if there's any information in [Adapters: iMessage](https://github.com/github/hubot/wiki/Adapter:-iMessage) that needs to be updated here before removing it complete. In particular, it looks like the wiki puts the `HUBOT_IMESSAGE_HANDLES` documentation closer to to the top of the docs.

Let me know if there's anything I can do to help!

**Comment by lazerwalker** [comment]
Glad to see the documentation getting some love! 

Things look peachy keen on my end — I've got some updating of the README to do based on recent experiences helping other folks get instances up and running, but that's unrelated to the current docs not needing to grab any other info from the old wiki page.

**Comment by technicalpickles** [comment]
Awesome, thanks!
