### ISSUE TITLE
is their something wrong with the imessage.coffee

### ISSUE THREAD

**Issue by runningdemo** [lazerwalker/hubot-imessage#2]
since I can't receive the response from my hubot that already running with the iMessage adapter. so I add some code to `iMessage.coffee` to print something to check, from the result I guess something maybe wrong. Here is the code:

```
 run: ->
    @allowedUsers = process.env.HUBOT_IMESSAGE_HANDLES.split(",")
    Pubsub.on 'message', (channel, dataString) =>
      data = JSON.parse(dataString)
      // added some code to print things out
      for key, value in data
          console.log "#{key}: #{value}"
```

Then I send message "ping" from "kidliaa@gmail.com" to my robot via iMessage.
My terminal output below: 

```
   message is missing
   userId is ping
   name is value
```

My robot is running at:
- os x 10.8.4
- iMessage 7.0.1(3322)

**Comment by lazerwalker** [comment]
I suspect this has been fixed by the recent changes to support Mavericks — if you didn't figure this out and are still interested, perhaps give it a try now?
