### ISSUE TITLE
AppleScript event handler Error

### ISSUE THREAD

**Issue by ghost** [lazerwalker/hubot-imessage#3]
An error occurred while executing an AppleScript event handler.

Event: Message Received
File: messageReceived.scpt
Error: The operation couldn’t be completed. PATHTOSCRIPT/messageReceived.scpt: execution error: sh: PATHTOHUBOTFOLDER/node_modules/hubot-imessage/src/imessage.coffee: Permission denied (126)

I get this error message from iMessage.

Mac OS X 10.9.1
iMessage 8.0.0

What can I do, to make this work?

**Comment by lazerwalker** [comment]
I suspect this has been fixed by recent changes. Try this again if you're still interested / weren't able to get it to work?
